apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.name }}
  labels:
    {{ include "tenant-namespace.labels" . }}
  annotations:
    {{ include "tenant-namespace.annotations" . }}
spec:
  limits:
    - type: Pod
      max:
        cpu: {{ .Values.limitsRange.cpu.max }}
        memory: {{ .Values.limitsRange.memory.max }}
      min:
        cpu: {{ .Values.limitsRange.cpu.min }}
        memory: {{ .Values.minMemory }}
    - type: Container
      max:
        cpu: {{ .Values.limitsRange.cpu.max }}
        memory: {{ .Values.limitsRange.memory.max }}
      min:
        cpu: {{ .Values.limitsRange.cpu.min }}
        memory: {{ .Values.limitsRange.memory.min }}
    - type: PersistentVolumeClaim
      max:
        storage: {{ .Values.limitsRange.storage.max }}
      min:
        storage: {{ .Values.limitsRange.storage.min }}
    - type: Service
      max:
        ports: {{ .Values.limitsRange.ports.max }}
      min:
        ports: {{ .Values.limitsRange.ports.min }}
