apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
  labels: 
{{ include "tenant-namespace.labels" . | indent 4 }}
  annotations:  
{{ include "tenant-namespace.annotations" . | indent 4 }}
