{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin
  labels: 
{{ include "tenant-namespace.labels" . | indent 4 }}
  annotations:  
{{ include "tenant-namespace.annotations" . | indent 4 }}
spec:
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: "{{ .Values.roleBinding.roleName }}"
  subjects:
    - kind: ServiceAccount
      name: "{{ include "tenant-namespace.serviceAccountName" . }}"
      namespace: "{{ .Values.namespace }}"
{{- end }}
