{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-sa
  labels:
{{- include "tenant-namespace.labels" . | nindent 4 }}
  annotations:  
{{ include "tenant-namespace.annotations" . | indent 4 }}
automountServiceAccountToken: "{{ .Values.serviceAccount.automount }}"
{{- end }}